### ISSUE TITLE
use loop Docker image from lightning lab

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/charts#14]
it seems there are 2 loop image here: https://hub.docker.com/u/lightninglabs

probably the latest one is the one we want to use

the reason it's probably better to use this image over the one we are already using is because there is a lower likelihood of the image being corrupt/evil compared to other anon sources

**Comment by nicolasburtey** [comment]
fixed @ntheile ?

**Comment by ntheile** [comment]
I think loopserver is the correct one according to this documentation:

https://github.com/lightninglabs/loop/blob/a4d343ca1bf3a3e9936adf09753587a08133ba2d/regtest/docker-compose.yml#L51 
 
After the server is up and running they have 3 options to call the server from a client:
1. The cli via loopd
2. GRPC
3. REST 

I am going thru these docs to get it up and running locally on my regtest environment via these docs https://github.com/lightninglabs/loop/tree/master/regtest 

I was able to get loopserver up via docker-compose in the galoy project.

```
  loopserver:
    image: lightninglabs/loopserver:latest
    restart: unless-stopped
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [lnd1]
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--lnd.host=lnd1:10009"
```
 I had to copy the macaroons over (probably going to run this in .envrc similar to the tls certs copying to the dev folder):

```
docker cp $container_id:/root/.lnd/data/chain/bitcoin/$NETWORK/ dev/lnd/macaroons 2> /dev/null
```

So now I just need to figure out how to call it via the GRPC or REST
